cache:
  key: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME"
  paths:
    - .composer/
    - .php_cs.cache

variables:
  COMPOSER_CACHE_DIR: ".composer"
  TYPO3_PATH_WEB: "$CI_PROJECT_DIR/.build/public"
  MYSQL_DATABASE: "typo3"
  MYSQL_ROOT_PASSWORD: "joh316"
  typo3DatabaseName: "typo3"
  typo3DatabaseHost: "mysql"
  typo3DatabaseUsername: "root"
  typo3DatabasePassword: "joh316"

before_script:
  - apk add git --update

stages:
  - lint
  - test
  - documentation

lint:cgl:
  image: $CI_REGISTRY/containers/phpunit-with-php-8.2:main
  stage: lint
  before_script:
    - composer remove typo3/cms-* --no-update
    - composer install --no-progress --no-ansi --no-interaction
  script:
    - vendor/bin/php-cs-fixer fix --config=Build/.php-cs-fixer.dist.php -v --dry-run --using-cache=no --path-mode=intersection ./
    - vendor/bin/typoscript-lint -c Build/typoscriptlint.yaml Configuration

lint:yaml:
  stage: lint
  image: python:alpine3.7
  before_script:
    - pip install yamllint==1.10.0
  script:
    - yamllint -c Build/yamllint.yaml Configuration/ Resources/

.lint_php: &lint_php
  stage: lint
  image: $CONTAINER_IMAGE
  script:
    - find *.php Classes Configuration Tests -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l

lint:php82:
  <<: *lint_php
  variables:
    CONTAINER_IMAGE: php:8.2-alpine

lint:php83:
  <<: *lint_php
  variables:
    CONTAINER_IMAGE: php:8.3-alpine

phpstan:analyse:
  image: $CI_REGISTRY/containers/phpunit-with-php-8.2:main
  stage: lint
  before_script:
    - composer install --no-progress --no-ansi --no-interaction
  script:
    - vendor/bin/phpstan analyse -c Build/phpstan.neon --memory-limit 256M

.test_php: &test_php
  stage: test
  services:
    - mysql:5
  image: $CONTAINER_IMAGE
  only:
    - branches
  before_script:
    - composer install --no-progress --no-ansi --no-interaction
  script:
    - vendor/bin/phpunit -c Build/UnitTests.xml

test:phpunit.php82:
  <<: *test_php
  variables:
    CONTAINER_IMAGE: $CI_REGISTRY/containers/phpunit-with-php-8.2:main

test:phpunit.php83:
  <<: *test_php
  variables:
    CONTAINER_IMAGE: $CI_REGISTRY/containers/phpunit-with-php-8.3:main

test:phpunit.php84:
  <<: *test_php
  variables:
    CONTAINER_IMAGE: $CI_REGISTRY/containers/phpunit-with-php-8.4:main

.test_codeception: &test_codeception
  stage: test
  image: $CONTAINER_IMAGE
  only:
    - branches
  before_script:
    - composer install --no-progress --no-ansi --no-interaction
  script:
    - mkdir -p .build/public/typo3temp/var/tests/acceptance-sqlite-dbs
    - export typo3DatabaseDriver=pdo_sqlite
    - export PROJECT_ROOT="$(pwd)"
    - export INSTANCE_PATH="$(pwd)/.build/web/typo3temp/var/tests/acceptance"
    - mkdir -p "$INSTANCE_PATH"
    - mkdir -p "$PROJECT_ROOT/.build/web/typo3temp/var/tests/acceptance-logs/"
    - vendor/bin/codecept build
    - vendor/bin/codecept run
  artifacts:
    paths:
      - .build
    expire_in: 1 day
    when: always

test:codeception:php82:
  <<: *test_codeception
  variables:
    CONTAINER_IMAGE: $CI_REGISTRY/containers/codeception-with-php-8.2:main
    GECKODRIVER_VERSION: v0.34.0

test:codeception:php83:
  <<: *test_codeception
  needs:
    - test:codeception:php82
  variables:
    CONTAINER_IMAGE: $CI_REGISTRY/containers/codeception-with-php-8.3:main
    GECKODRIVER_VERSION: v0.34.0

test:codeception:php84:
  <<: *test_codeception
  needs:
    - test:codeception:php83
  variables:
    CONTAINER_IMAGE: $CI_REGISTRY/containers/codeception-with-php-8.4:main
    GECKODRIVER_VERSION: v0.34.0

documentation:
  stage: documentation
  image:
    name: ghcr.io/typo3-documentation/render-guides:latest
    entrypoint: [ "" ]
  script:
    - mkdir -p Documentation-GENERATED-temp
    - /opt/guides/entrypoint.sh --config=Documentation --no-progress --fail-on-log
  before_script: []
  artifacts:
    paths:
      - Documentation-GENERATED-temp/
    expire_in: 1 day
    when: always
