services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Extcode\CartBooks\:
    resource: '../Classes/*'
    exclude: '../Classes/Widgets/*'

  Extcode\CartBooks\Domain\Finisher\Cart\AddToCartFinisher:
    public: true
