services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Extcode\CartBooks\:
    resource: '../Classes/*'

  Extcode\CartBooks\EventListener\Order\Stock\HandleStock:
    tags:
      - name: event.listener
        identifier: 'cart-books--order--stock--handle-stock'
        event: Extcode\Cart\Event\Order\StockEvent

  Extcode\CartBooks\EventListener\Order\Stock\FlushCache:
    tags:
      - name: event.listener
        identifier: 'cart-books--order--stock--flush-cache'
        event: Extcode\Cart\Event\Order\StockEvent
        after: 'cart-books--order--stock--handle-stock'

  Extcode\CartBooks\EventListener\RetrieveProductsFromRequest:
    tags:
      - name: event.listener
        identifier: 'cart-books--retrieve-products-from-request'
        event: Extcode\Cart\Event\RetrieveProductsFromRequestEvent

  Extcode\CartBooks\EventListener\CheckProductAvailability:
    tags:
      - name: event.listener
        identifier: 'cart-books--check-product-availability'
        event: Extcode\Cart\Event\CheckProductAvailabilityEvent
