name: CI
on:
  - pull_request
jobs:
  check-composer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate composer.json
        run: composer validate

  php-linting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - 8.2
          - 8.3
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php-version }}"
          tools: composer:v2

      - name: PHP lint
        run: "find *.php Classes Configuration Tests -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l"

  coding-guideline:
    runs-on: ubuntu-latest
    needs:
      - php-linting
    steps:
      - uses: actions/checkout@v4

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          tools: composer:v2

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Coding Guideline
        run: vendor/bin/php-cs-fixer fix --config=Build/.php-cs-fixer.dist.php -v --dry-run --using-cache=no --path-mode=intersection ./

  code-quality:
    runs-on: ubuntu-latest
    needs:
      - php-linting
    strategy:
      matrix:
        include:
          - php-version: '8.2'
          - php-version: '8.3'
          - php-version: '8.4'
    steps:
      - uses: actions/checkout@v4

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php-version }}"
          tools: composer:v2

      - name: Install dependencies with expected TYPO3 version
        run: |-
          composer remove --dev ssch/typo3-rector \
          && composer require typo3/cms-install "*" \
          && composer install --no-progress --no-ansi --no-interaction

      - name: Code Quality (by PHPStan)
        run: vendor/bin/phpstan analyse -c Build/phpstan.neon

  tests-acceptance:
    runs-on: ubuntu-latest
    needs:
      - coding-guideline
      - code-quality
    steps:
      - uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Run Unit Tests PHP8.2
        run: nix-shell --arg phpVersion \"php82\" --pure --run project-test-unit

      - name: Run Unit Tests PHP8.3
        run: nix-shell --arg phpVersion \"php83\" --pure --run project-test-unit

      - name: Run Unit Tests PHP8.4
        run: nix-shell --arg phpVersion \"php84\" --pure --run project-test-unit

      - name: Run Acceptance Tests PHP8.2
        run: nix-shell --arg phpVersion \"php82\" --pure --run project-test-acceptance

      - name: Run Acceptance Tests PHP8.3
        run: nix-shell --arg phpVersion \"php83\" --pure --run project-test-acceptance

      - name: Run Acceptance Tests PHP8.4
        run: nix-shell --arg phpVersion \"php84\" --pure --run project-test-acceptance
